name: 'Pull Request Description Enforcement'
description: 'github action for enforcing description on pull requests'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
